const ADD_TOKEN = "ADD_TOKEN";
const ADD_USERINFO = "ADD_USERINFO";
const CHANGE_LOGIN = "CHANGE_LOGIN";
const ADD_SHOP = "ADD_SHOP";
const CHANGE_SHOP = "CHANGE_SHOP";
export { ADD_TOKEN, ADD_USERINFO, CHANGE_LOGIN, ADD_SHOP, CHANGE_SHOP };
